'use client';
import {useCallback,type ReactNode} from 'react';
import {api,useData,Heading,Loading,Retry,type Config} from '../components/client';
const labels:Record<string,string>={operatorContact:'운영자 연락처',responsibleContact:'개인정보 책임자 연락처',processors:'수탁자와 업무',mailRoute:'메일 처리 경로·위탁/이전 안내',deletionInstructions:'열람·정정·삭제 요청 방법',cookies:'쿠키',items:'수집 항목',purposes:'처리 목적',retention:'보관 기간'};
const policies=[['학교 이메일·계정 ID','인증에 사용하며 탈퇴 또는 서비스 종료 시 삭제합니다.'],['선택 프로필','표시 이름·학과·입학 연도·관심 주제는 선택입니다. 미입력으로 이용할 수 있고, 수정·삭제·동의 철회가 즉시 반영됩니다. 계정과 함께 삭제합니다.'],['학기 가능 시간·모임별 예외','시간 조율에 사용하며 학기 종료 후 30일 이내 삭제합니다. 모임별 예외는 모임 삭제 시 함께 삭제합니다.'],['모임·참여·제안/수락·코멘트','확정일로부터 30일, 미정은 생성일로부터 90일 보관합니다. 생성 후 120일을 절대 상한으로 적용하며 만료 시 조회에서 제외하고 일일 삭제로 24시간 이내 파기합니다.'],['신고·차단','신고는 접수일부터 90일, 신고자 탈퇴 또는 대상 삭제 시 즉시 삭제합니다. 첨부·코멘트 사본은 수집하지 않습니다. 차단은 해제 또는 한쪽 탈퇴 시 삭제합니다. 최근 90일 미기각 사용자 신고가 서로 다른 3명에 도달하면 개설이 제한되며, 3명 미만으로 줄면 자동 해제합니다. 운영자는 3영업일 이내 검토하고 연락처로 이의 제기를 받습니다.'],['인증·쿠키','OTP는 HMAC으로 보관하며 10분 만료, 인증 성공·재발급 시 폐기합니다. 인증 남용 방지용 IP HMAC·주소별 횟수는 1시간 후 삭제합니다. 원문 IP를 보관하지 않습니다. 로그인 세션은 7일, 로그아웃·탈퇴 시 폐기합니다. 로그인·사전 인증 쿠키는 HttpOnly·SameSite=Lax이며 운영 환경에서 Secure를 적용합니다. 사전 인증 쿠키는 10분 유지합니다.'],['오류·접근 기록','오류 로그는 요청 ID·오류 코드·시각만 14일 보관합니다. 개인정보 취급자 접근 기록은 운영자 ID·시각·대상 내부 ID·작업·사유를 별도로 1년 보관합니다. 이메일·본문·OTP·세션 토큰을 로그에 기록하지 않습니다.'],['탈퇴·백업','프로필의 탈퇴 메뉴에서 계정·시간·참여·코멘트·신고·차단·개설 모임을 삭제하고 전 세션을 폐기합니다. 백업 잔존은 최대 7일이며 복구 용도로만 사용합니다. 내부 ID·삭제 시각의 복구용 삭제 목록은 별도 8일 보관하고 복원 전 삭제를 재적용합니다.'],['수집하지 않는 정보','광고·행동 추적·정밀 위치·연락처·편입 여부는 수집하지 않습니다. 외부 기관에 실사용자 정보·집계를 제공하지 않습니다.']];
function NoticeValue({value}:{value:unknown}):ReactNode{if(value===null||value===undefined)return '미설정';if(Array.isArray(value))return <ul>{value.map((v,i)=><li key={i}><NoticeValue value={v}/></li>)}</ul>;if(typeof value==='object')return <dl>{Object.entries(value).map(([key,v])=><div key={key}><dt>{labels[key]??key}</dt><dd><NoticeValue value={v}/></dd></div>)}</dl>;return String(value);}
export default function Privacy(){
  const load=useCallback(async(signal:AbortSignal)=>(await api<Config>('configuration','GET',undefined,undefined,signal)).data,[]);const state=useData(load),c=state.data;
  return <article className="narrow prose"><Heading title="개인정보 처리 안내" description="필수 인증 정보와 선택 프로필을 구분하고, 필요한 기간만 보관합니다."/><Retry error={state.error} reload={state.reload}/>{!c&&state.loading&&<Loading/>}{c&&<><section className="time-banner"><h2>{c.registrationAvailable?'공개 운영 설정':'운영 준비 중'}</h2><p>{c.registrationAvailable?`학교: ${c.school?.name} · 고지 버전: ${c.privacyVersion}`:'실제 운영자·위탁 정보와 삭제 검증이 완료되기 전에는 가입을 열지 않습니다. 아래 내용은 제품 정책이며 실제 운영 연결의 완료를 뜻하지 않습니다.'}</p></section><h2>수집·목적·보관·삭제</h2><dl>{policies.map(([name,description])=><div key={name}><dt>{name}</dt><dd>{description}</dd></div>)}</dl><h2>운영자·위탁 및 실제 고지</h2><p className="help">AWS와 메일 업무의 실제 계약·처리 경로에 따른 위탁/이전 고지를 확인합니다. 서울 리전만으로 국외 이전이 없다고 단정하지 않습니다.</p><dl>{Object.entries(labels).map(([key,label])=><div key={key}><dt>{label}</dt><dd className="policy-text"><NoticeValue value={c.privacyNotice?.[key]}/></dd></div>)}</dl><p>서비스 종료 시 신규 가입을 닫고 원본을 삭제합니다. 연장은 별도 결정·고지합니다.</p></>}</article>;
}
