'use client';
import {useCallback,useState} from 'react';
import {api,useData,Form,Heading,Loading,Retry,Slots,selectedSlots,ProfileText,type Config,type Me,type Profile} from '../components/client';
type Availability={registered:boolean,slots:number[]};
export default function ProfilePage(){
  const load=useCallback(async(signal:AbortSignal)=>{const c=(await api<Config>('configuration','GET',undefined,undefined,signal)).data;const me=(await api<Me>('me','GET',undefined,undefined,signal)).data;const times=c.term?(await api<Availability>(`me/availability/${c.term.id}`,'GET',undefined,undefined,signal)).data:null;return {c,me,times};},[]);
  const state=useData(load),d=state.data;
  return <div className="profile-page"><Heading title="내 시간·프로필" description="이번 학기에 모임을 제안받을 수 있는 시간을 알려주세요."/><Retry error={state.error} reload={state.reload}/>{!d&&state.loading&&<Loading/>}{d&&<><p className="school-label break-word">{d.c.school?.name} · {d.me.email}</p><section className="detail-section"><h2>학기 가능 시간</h2>{d.c.term?<Form dirtyGuard submit={async f=>{await api(`me/availability/${d.c.term!.id}`,'PUT',{slots:selectedSlots(f)});state.reload();}} label="가능 시간 저장"><p className="help">{d.c.term.startsOn} ~ {d.c.term.endsOn} · {d.times?.registered?'등록한 시간을 모임마다 재사용합니다.':'아직 시간을 등록하지 않았습니다.'}</p><Slots key={JSON.stringify(d.times?.slots)} slots={d.c.term.slots} selected={d.times?.slots}/></Form>:<p>학기가 아직 설정되지 않았습니다.</p>}</section><section className="detail-section"><h2>선택 프로필</h2><p className="help">학과·입학 연도·관심 주제만 다른 참여자에게 공개합니다. 표시 이름은 본인 관리용입니다.</p><ProfileForm key={JSON.stringify([d.me.displayName,d.me.department,d.me.entryYear,d.me.interests,d.me.optionalProfileConsent])} me={d.me} c={d.c} reload={state.reload}/></section><Blocks/><section className="account-controls"><h2>계정 관리</h2><Form submit={async()=>{await api('auth/sessions/current','DELETE');return '/login';}} label="로그아웃"><p className="help">현재 세션을 종료합니다.</p></Form><details><summary>탈퇴 및 개인정보 삭제</summary><Form danger label="탈퇴하고 삭제" submit={async f=>{await api('me','DELETE',{confirmDeletion:f.get('confirmDeletion')==='on'});return '/login';}}><p>계정·시간·참여·코멘트·신고·차단·개설 모임을 삭제하고 모든 세션을 종료합니다. 되돌릴 수 없습니다.</p><label className="check-line"><input name="confirmDeletion" type="checkbox" required/>삭제 내용을 확인했습니다.</label></Form></details></section></>}</div>;
}
function ProfileForm({me,c,reload}:{me:Me,c:Config,reload:()=>void}){
  const [consent,setConsent]=useState(me.optionalProfileConsent);
  return <Form dirtyGuard label="프로필 저장" submit={async f=>{await api('me','PATCH',consent?{optionalProfileConsent:true,displayName:String(f.get('displayName')).trim()||null,department:String(f.get('department'))||null,entryYear:f.get('entryYear')?Number(f.get('entryYear')):null,interests:String(f.get('interests')).split(',').map(s=>s.trim()).filter(Boolean)}:{optionalProfileConsent:false});reload();}}><label className="check-line"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>선택 프로필 수집·공개에 동의합니다. 동의를 철회해 저장하면 선택 정보가 삭제됩니다.</span></label><fieldset className="stack" disabled={!consent}><label htmlFor="displayName">표시 이름 (선택)</label><input id="displayName" name="displayName" maxLength={100} defaultValue={me.displayName??''}/><label htmlFor="department">학과 (선택)</label><select id="department" name="department" defaultValue={me.department??''}><option value="">선택 안 함</option>{c.school?.departments.map(d=><option key={d}>{d}</option>)}</select><label htmlFor="entryYear">입학 연도 (선택)</label><select id="entryYear" name="entryYear" defaultValue={me.entryYear??''}><option value="">선택 안 함</option>{c.school?.entryYears.map(y=><option key={y} value={y}>{y}</option>)}</select><label htmlFor="interests">관심 주제 (선택, 쉼표로 구분, 최대 10개)</label><input id="interests" name="interests" defaultValue={me.interests.join(', ')} maxLength={1009}/></fieldset></Form>;
}
function Blocks(){
  const [cursor,setCursor]=useState<string|null>(null),[previous,setPrevious]=useState<(string|null)[]>([]);
  const load=useCallback(async(signal:AbortSignal)=>{const r=await api<{userId:string,profile:Profile}[]>(`me/blocks${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`,'GET',undefined,undefined,signal);return {data:r.data,nextCursor:r.nextCursor};},[cursor]);const state=useData(load);
  return <section className="detail-section"><h2>차단 관리</h2><Retry error={state.error} reload={state.reload}/>{state.loading&&!state.data&&<Loading/>}{state.data?.data.length===0&&<p className="muted">차단한 사용자가 없습니다.</p>}{state.data?.data.map((b,i)=><div key={b.userId}><p>차단 사용자 {previous.length*20+i+1} · <ProfileText profile={b.profile}/></p><Form label="차단 해제" submit={async()=>{await api(`me/blocks/${b.userId}`,'DELETE');state.reload();}}><span className="help">해제하면 상대 모임이 다시 표시됩니다.</span></Form></div>)}<div className="form-actions">{previous.length>0&&<button className="button" onClick={()=>{setCursor(previous.at(-1)!);setPrevious(p=>p.slice(0,-1));}}>이전</button>}{state.data?.nextCursor&&<button className="button" onClick={()=>{setPrevious(p=>[...p,cursor]);setCursor(state.data!.nextCursor!);}}>다음</button>}</div></section>;
}
