'use client';
import {useCallback,useState,type FormEvent} from 'react';
import {api,useData,Heading,Loading,Retry,kinds,slotLabel,type Config,type Meeting} from './components/client';
export default function Home(){
  const [filter,setFilter]=useState({topic:'',type:'',overlapOnly:false}),[cursor,setCursor]=useState<string|null>(null),[previous,setPrevious]=useState<(string|null)[]>([]);
  const config=useData(useCallback(async(signal:AbortSignal)=>(await api<Config>('configuration','GET',undefined,undefined,signal)).data,[]));
  const load=useCallback(async(signal:AbortSignal)=>{const q=new URLSearchParams({topic:filter.topic,overlapOnly:String(filter.overlapOnly)});if(filter.type)q.set('type',filter.type);if(cursor)q.set('cursor',cursor);const r=await api<Meeting[]>(`meetings?${q}`,'GET',undefined,undefined,signal);return {meetings:r.data,nextCursor:r.nextCursor};},[filter,cursor]);const state=useData(load);
  function search(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setCursor(null);setPrevious([]);setFilter({topic:String(f.get('topic')),type:String(f.get('type')),overlapOnly:f.get('overlap')==='on'});}
  return <><Heading title="함께할 사람을 찾아요" description="시간이 정해지지 않아도 괜찮아요. 관심사부터 모으고 함께 조율해요."><a className="button primary" href="/meetings/new">모임 열기</a></Heading><div className="workspace"><aside className="availability-summary"><h2>{config.data?.school?.name??'같은 학교, 같은 관심사'}</h2><p>가능 시간은 모임 제안을 받아도 되는 시간입니다. 참여는 직접 결정해요.</p><a className="text-link" href="/profile">내 가능 시간 등록·수정 →</a>{config.data&&!config.data.registrationAvailable&&<p>신규 가입을 준비 중입니다.</p>}<Retry error={config.error} reload={config.reload}/></aside><section><h2>모임 찾기</h2><form className="stack" onSubmit={search}><label htmlFor="topic">관심 주제</label><input id="topic" name="topic" maxLength={100} placeholder="찾고 싶은 주제"/><label htmlFor="type">모임 유형</label><select id="type" name="type"><option value="">전체</option>{Object.entries(kinds).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select><label className="check-line"><input type="checkbox" name="overlap"/>내 가능 시간과 겹치는 모임만</label><button className="button" type="submit">검색</button></form><Retry error={state.error} reload={state.reload}/>{state.loading&&<Loading/>}{!state.loading&&state.data&&<>{state.data.meetings.length===0?<div className="empty-state"><h3>아직 모임이 없어요</h3><p>원하는 주제로 첫 모임을 열어보세요.</p><a className="button primary" href="/meetings/new">모임 열기</a></div>:<ul className="meetings">{state.data.meetings.map(m=><li className="meeting-row" key={m.id}><div className="meeting-top"><span className="badge">{kinds[m.type]}</span><span>{m.memberCount}/{m.capacity}명</span></div><h3><a href={`/meetings/${m.id}`}>{m.topic}</a></h3><p className="meeting-meta">{m.place.name} · {m.confirmation?`${m.confirmation.date} ${slotLabel(m.confirmation.slot)}`:m.state==='proposing'?'시간 제안 조율 중':'시간 미정'}</p><div className="meeting-bottom"><p className="overlap">{m.overlapsMyAvailability?'✓ 내 시간과 겹쳐요':'시간을 함께 조율해요'}</p><a className="text-link" href={`/meetings/${m.id}`}>모임 보기 →</a></div></li>)}</ul>}<div className="form-actions">{previous.length>0&&<button className="button" onClick={()=>{setCursor(previous.at(-1)!);setPrevious(p=>p.slice(0,-1));}}>이전</button>}{state.data.nextCursor&&<button className="button" onClick={()=>{setPrevious(p=>[...p,cursor]);setCursor(state.data!.nextCursor!);}}>다음</button>}</div></>}</section></div></>;
}
