'use client';
import {useCallback,useEffect,useState} from 'react';
import {api,useData,Form,Loading,Retry,RequestError,type Config} from '../components/client';
export default function Login() {
  const load=useCallback(async(signal:AbortSignal)=>(await api<Config>('configuration','GET',undefined,undefined,signal)).data,[]);
  const state=useData(load),[challenge,setChallenge]=useState<{id:string,email:string,expires:number,retry:number}>(),[clock,setClock]=useState(Date.now());
  useEffect(()=>{if(!challenge)return;const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[challenge]);
  const c=state.data;
  async function issue(email:string) {try{const {data}=await api<{challengeId:string,expiresIn:number,retryAfter:number}>('auth/otp-challenges','POST',{email});setChallenge({id:data.challengeId,email,expires:Date.now()+data.expiresIn*1000,retry:Date.now()+data.retryAfter*1000});setClock(Date.now());}catch(e){if(e instanceof RequestError && e.retryAfter && challenge)setChallenge({...challenge,retry:Date.now()+e.retryAfter*1000});throw e;}}
  return <div className="auth-layout"><section className="auth-intro"><p className="school-label">{c?.school?.name??'같은 학교에서'}</p><h1>같은 관심사,<br/>함께할 시간.</h1><p className="lede">한 번 등록한 가능 시간으로 공부 동료를 만나보세요.</p><div className="intro-types"><span>모각공</span><span>커피챗</span><span>런치챗</span></div></section><section className="auth-panel"><h2>학교 이메일로 시작하기</h2><p className="muted">6자리 인증번호는 10분 동안 유효합니다.</p><Retry error={state.error} reload={state.reload}/>{!c&&state.loading&&<Loading/>}{c&&(!c.registrationAvailable?<div className="setup-state"><h3>운영 준비 중입니다</h3><p>학교 설정과 개인정보 안내·출시 검증을 마친 뒤 인증을 시작할 수 있습니다.</p><a href="/privacy">개인정보 처리 안내</a></div>:<><Form submit={async f=>{await issue(String(f.get('email')));}} label={challenge?'다른 이메일로 인증번호 받기':'인증번호 받기'}><label htmlFor="email">학교 이메일</label><input id="email" name="email" type="email" autoComplete="email" maxLength={254} required defaultValue={challenge?.email}/></Form>{challenge&&<><p className="help break-word">{challenge.email}로 보냈습니다. 남은 시간 {Math.max(0,Math.ceil((challenge.expires-clock)/1000))}초</p><Form disabled={clock>=challenge.expires} submit={async f=>{await api('auth/sessions','POST',{challengeId:challenge.id,code:String(f.get('code')),privacyVersion:c.privacyVersion,privacyAcknowledged:f.get('privacy')==='on'});return '/profile';}} label="인증하고 시작하기"><label htmlFor="code">6자리 인증번호</label><input id="code" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required/><label className="check-line"><input name="privacy" type="checkbox" required/><span><a href="/privacy" target="_blank" rel="noreferrer">개인정보 처리 안내</a>를 확인했으며 필수 처리에 동의합니다. 선택 프로필 없이도 이용할 수 있습니다.</span></label><p className="help">{clock>=challenge.expires?'인증번호가 만료되었습니다. 다시 받아주세요.':'오입력 5회 시 인증번호가 폐기됩니다.'}</p></Form><Form disabled={clock<challenge.retry} submit={async()=>{await issue(challenge.email);}} label="인증번호 다시 받기"><p className="help">재발송까지 {Math.max(0,Math.ceil((challenge.retry-clock)/1000))}초</p>{clock<challenge.retry&&<p>60초 간격으로 재발송할 수 있습니다.</p>}</Form></>}</>)}</section></div>;
}
